-- require("user.plugins.lsp-ts-utils")
require("user.plugins.typescript-config")
require("user.plugins.neotest-config")
-- require("user.plugins.winbar-config")
require("user.plugins.treestitter-context-config")
require("user.plugins.tundra-config")
require("user.plugins.package-info-config")
-- colors
require("user.plugins.catppucin")
-- require("user.plugins.material-config")
-- require("user.plugins.saga")
-- require("user.plugins.navigator-config")
